plugins {
    id 'java'
    id 'org.springframework.boot' version '2.7.18'
    id 'io.spring.dependency-management' version '1.0.15.RELEASE'
}

group = 'com.github.bgrebennikov'
version = '0.0.1-SNAPSHOT'
description = 'RecommendationService'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    runtimeOnly 'com.h2database:h2'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.springdoc:springdoc-openapi-ui:1.7.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    implementation 'org.jspecify:jspecify:1.0.0'

    runtimeOnly 'com.h2database:h2:2.2.224'
}

tasks.named('test') {
    useJUnitPlatform()
}
