spring.application.name=RecommendationService

application.recommendations-db.url=jdbc:h2:file:./transaction

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:recommendations}
spring.datasource.username=${DB_LOGIN:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

spring.cache.type=redis
spring.cache.redis.time-to-live=${REDIS_CACHE_TTL:600000}
spring.cache.redis.cache-null-values=false