spring.application.name=RecommendationService

application.recommendations-db.url=jdbc:h2:file:./transaction

application.postgres-db.url=${DB_HOST}
application.postgres-db.username=${DB_USERNAME}
application.postgres-db.password=${DB_PASSWORD}
