spring.application.name=RecommendationService

spring.datasource.url=jdbc:h2:file:./src/main/resources/transaction;ACCESS_MODE_DATA=r
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=